/* Automatically generated by configure - do not modify */

#define TCC_VERSION "0.9.28rc"

#define CC_NAME CC_gcc
#define GCC_MAJOR 15
#define GCC_MINOR 1

#if !(TCC_TARGET_I386 || TCC_TARGET_X86_64 || TCC_TARGET_ARM || TCC_TARGET_ARM64 || TCC_TARGET_RISCV64 || TCC_TARGET_C67)
#define TCC_TARGET_X86_64 1
#define TCC_TARGET_PE 1
#endif

#define CONFIG_TCC_PREDEFS 0
