/* Encoding gate for the SSE / SSE2 entries of x86_64-asm.h.
   sse_sse2_list.s is assembled by TCC and linked with this file; the code
   between sse_list and sse_list_end must be byte for byte the bytes in
   sse_sse2_expected.h.  Those bytes were checked once against clang with
   ..\manual\asm_sse_sse2_vs_clang.bat (the two disassemble to the same text);
   this gate keeps them from changing.

   "sse_sse2_check dump" prints the bytes as a new sse_sse2_expected.h.  Only
   regenerate it after asm_sse_sse2_vs_clang.bat passes. */
#include <stdio.h>
#include <string.h>

extern unsigned char sse_list[];
extern unsigned char sse_list_end[];

#include "sse_sse2_expected.h"

int main(int argc, char **argv)
{
    size_t len = (size_t)(sse_list_end - sse_list);
    size_t i;
    if (argc > 1 && strcmp(argv[1], "dump") == 0) {
        printf("/* Generated by \"sse_sse2_check dump\" - do not edit by hand. */\n");
        printf("static const unsigned char sse_expected[%u] = {", (unsigned)len);
        for (i = 0; i < len; i++)
            printf("%s0x%02x,", (i % 16) ? " " : "\n    ", sse_list[i]);
        printf("\n};\n");
        return 0;
    }
    if (len != sizeof sse_expected) {
        printf("ASM_SSE_SSE2: length %u, expected %u\n", (unsigned)len, (unsigned)sizeof sse_expected);
        return 1;
    }
    for (i = 0; i < len; i++) {
        if (sse_list[i] != sse_expected[i]) {
            printf("ASM_SSE_SSE2: byte %u is 0x%02x, expected 0x%02x\n", (unsigned)i, sse_list[i], sse_expected[i]);
            return 2;
        }
    }
    return 0;
}
